# Makefile for the kernel module subdirectory
# This file must be placed inside the 'kern_mod' directory.

# Specify the object file for your kernel module
# Note: No path here, as this Makefile is already within kern_mod
obj-m += cred_mod.o
